// GENERATED by scripts/build_basemap.py — do not edit by hand.
//
// Centroids of Gujarat's district boundaries, used to place a camera whose own position is
// unverified. A camera placed here is ALWAYS drawn hollow with an uncertainty circle and
// labelled 'position unverified' — the centroid is an admission of ignorance, not a location.

export interface Centroid {
  lat: number;
  lng: number;
}

export const DISTRICT_CENTROIDS: Record<string, Centroid> = {
  "Ahmadabad": { lat: 22.72731, lng: 72.20335 },
  "Ahmedabad": { lat: 22.72731, lng: 72.20335 },
  "Amreli": { lat: 21.42126, lng: 71.26357 },
  "Anand": { lat: 22.45233, lng: 72.79526 },
  "Aravalli": { lat: 23.65821, lng: 73.16656 },
  "Banas Kantha": { lat: 24.28106, lng: 72.03934 },
  "Banaskantha": { lat: 24.28106, lng: 72.03934 },
  "Bharuch": { lat: 21.78751, lng: 72.92332 },
  "Bhavnagar": { lat: 21.67082, lng: 71.84985 },
  "Botad": { lat: 21.67082, lng: 71.84985 },
  "Chhota Udaipur": { lat: 22.22644, lng: 73.54118 },
  "Dahod": { lat: 22.91016, lng: 74.01985 },
  "Devbhoomi Dwarka": { lat: 22.24829, lng: 69.92704 },
  "Gandhinagar": { lat: 23.20806, lng: 72.69962 },
  "Gir Somnath": { lat: 21.21375, lng: 70.56785 },
  "Jamnagar": { lat: 22.24829, lng: 69.92704 },
  "Junagadh": { lat: 21.21375, lng: 70.56785 },
  "Kachchh": { lat: 23.62281, lng: 70.00492 },
  "Kheda": { lat: 22.87646, lng: 73.02348 },
  "Kutch": { lat: 23.62281, lng: 70.00492 },
  "Mahesana": { lat: 23.57962, lng: 72.4963 },
  "Mahisagar": { lat: 22.85288, lng: 73.60851 },
  "Mehsana": { lat: 23.57962, lng: 72.4963 },
  "Morbi": { lat: 22.25502, lng: 70.79212 },
  "Narmada": { lat: 21.71155, lng: 73.65744 },
  "Navsari": { lat: 20.81256, lng: 73.10341 },
  "Panch Mahals": { lat: 22.85288, lng: 73.60851 },
  "Panchmahal": { lat: 22.85288, lng: 73.60851 },
  "Patan": { lat: 23.76791, lng: 71.80014 },
  "Porbandar": { lat: 21.63773, lng: 69.80213 },
  "Rajkot": { lat: 22.25502, lng: 70.79212 },
  "Sabar Kantha": { lat: 23.65821, lng: 73.16656 },
  "Sabarkantha": { lat: 23.65821, lng: 73.16656 },
  "Surat": { lat: 21.23445, lng: 73.31115 },
  "Surendranagar": { lat: 22.79469, lng: 71.55247 },
  "The Dangs": { lat: 20.79856, lng: 73.70615 },
  "Vadodara": { lat: 22.22644, lng: 73.54118 },
  "Valsad": { lat: 20.41819, lng: 73.11856 },
};

/** Last resort when even the district is unknown. */
export const GUJARAT_CENTROID: Centroid = { lat: 22.50039, lng: 72.2091 };
