// GENERATED by scripts/build_basemap.py — do not edit by hand.
//
// Centroids of Gujarat's district boundaries, used to place a camera whose own position is
// unverified. A camera placed here is ALWAYS drawn hollow with an uncertainty circle and
// labelled 'position unverified' — the centroid is an admission of ignorance, not a location.

export interface Centroid {
  lat: number;
  lng: number;
}

export const DISTRICT_CENTROIDS: Record<string, Centroid> = {
  "Ahmadabad": { lat: 22.70999, lng: 72.19602 },
  "Ahmedabad": { lat: 22.70999, lng: 72.19602 },
  "Amreli": { lat: 21.42276, lng: 71.25082 },
  "Anand": { lat: 22.45369, lng: 72.78822 },
  "Aravalli": { lat: 23.65933, lng: 73.16368 },
  "Banas Kantha": { lat: 24.28356, lng: 72.03184 },
  "Banaskantha": { lat: 24.28356, lng: 72.03184 },
  "Bharuch": { lat: 21.78666, lng: 72.9256 },
  "Bhavnagar": { lat: 21.66583, lng: 71.83982 },
  "Botad": { lat: 21.66583, lng: 71.83982 },
  "Chhota Udaipur": { lat: 22.23316, lng: 73.53309 },
  "Dahod": { lat: 22.85727, lng: 74.11595 },
  "Devbhoomi Dwarka": { lat: 22.2496, lng: 69.91515 },
  "Dohad": { lat: 22.85727, lng: 74.11595 },
  "Gandhinagar": { lat: 23.25495, lng: 72.69236 },
  "Gir Somnath": { lat: 21.22165, lng: 70.55416 },
  "Jamnagar": { lat: 22.2496, lng: 69.91515 },
  "Junagadh": { lat: 21.22165, lng: 70.55416 },
  "Kachchh": { lat: 23.62603, lng: 69.99679 },
  "Kheda": { lat: 22.87632, lng: 73.01675 },
  "Kutch": { lat: 23.62603, lng: 69.99679 },
  "Mahesana": { lat: 23.60906, lng: 72.46199 },
  "Mahisagar": { lat: 22.90396, lng: 73.66418 },
  "Mehsana": { lat: 23.60906, lng: 72.46199 },
  "Morbi": { lat: 22.26231, lng: 70.77491 },
  "Narmada": { lat: 21.73542, lng: 73.64748 },
  "Navsari": { lat: 20.8152, lng: 73.08969 },
  "Panch Mahals": { lat: 22.90396, lng: 73.66418 },
  "Panchmahal": { lat: 22.90396, lng: 73.66418 },
  "Patan": { lat: 23.76934, lng: 71.75242 },
  "Porbandar": { lat: 21.65332, lng: 69.77806 },
  "Rajkot": { lat: 22.26231, lng: 70.77491 },
  "Sabar Kantha": { lat: 23.65933, lng: 73.16368 },
  "Sabarkantha": { lat: 23.65933, lng: 73.16368 },
  "Surat": { lat: 21.26655, lng: 73.07409 },
  "Surendranagar": { lat: 22.79819, lng: 71.54018 },
  "Tapi": { lat: 21.19156, lng: 73.63113 },
  "The Dangs": { lat: 20.79788, lng: 73.69904 },
  "Vadodara": { lat: 22.23316, lng: 73.53309 },
  "Valsad": { lat: 20.41845, lng: 73.11465 },
};

/** Last resort when even the district is unknown. */
export const GUJARAT_CENTROID: Centroid = { lat: 22.48418, lng: 72.28309 };
